import '../models/form_field_schema.dart';

class BankSchemas {
  static final List<FormFieldSchema> askblSchema = [
    FormFieldSchema(key: 'inspected_date', label: 'Inspected Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'print_date', label: 'Print Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'representative_cnic', label: 'Representative Cnic', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_at', label: 'Inspected At', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'title_of_ownership', label: 'Title Of Ownership', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_make', label: 'Car Make', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_model', label: 'Car Model', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_color', label: 'Car Color', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'bank_name', label: 'Bank Name', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'car_class', label: 'Car Class', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'air_conditionar_available', label: 'Air Conditionar Available', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'air_conditionar_working', label: 'Air Conditionar Working', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration', label: 'Car Registration', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration_date', label: 'Car Registration Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_cng_kit', label: 'Car Cng Kit', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'genre', label: 'Genre', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'hypothecated_with', label: 'Hypothecated With', type: 'text', section: 'Document Review'),
    FormFieldSchema(key: 'car_engine_no', label: 'Car Engine No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'body_type', label: 'Body Type', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_capacity', label: 'Car Engine Capacity', type: 'number', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_chassis_no', label: 'Car Chassis No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'odometer_reading', label: 'Odometer Reading', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'rim_type', label: 'Rim Type', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufactured', label: 'Manufactured', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'transmission', label: 'Transmission', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'feul_type', label: 'Feul Type', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'accessories', label: 'Accessories', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_drive', label: 'Car Drive', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_hybrid', label: 'Is Hybrid', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'body_condition', label: 'Body Condition', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'engine_condition', label: 'Engine Condition', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'steering_control', label: 'Steering Control', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'axle', label: 'Axle', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'suspension', label: 'Suspension', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'seating_capacity', label: 'Seating Capacity', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'transmission_system', label: 'Transmission System', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'electric_system', label: 'Electric System', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tyres', label: 'Tyres', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'any_leaks', label: 'Any Leaks', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'major_defects', label: 'Major Defects', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'chassis_repaired', label: 'Chassis Repaired', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'external_body', label: 'External Body', type: 'text', section: 'External Conditions of Vehicle'),
    FormFieldSchema(key: 'external_bonnet', label: 'External Bonnet', type: 'text', section: 'External Conditions of Vehicle'),
    FormFieldSchema(key: 'external_doors', label: 'External Doors', type: 'text', section: 'External Conditions of Vehicle'),
    FormFieldSchema(key: 'internal_dashboard', label: 'Internal Dashboard', type: 'text', section: 'Internal Conditions of Vehicle'),
    FormFieldSchema(key: 'internal_roof', label: 'Internal Roof', type: 'text', section: 'Internal Conditions of Vehicle'),
    FormFieldSchema(key: 'internal_seats', label: 'Internal Seats', type: 'text', section: 'Internal Conditions of Vehicle'),
    FormFieldSchema(key: 'overall_condition', label: 'Overall Condition', type: 'text', section: 'Internal Conditions of Vehicle'),
    FormFieldSchema(key: 'negative_remarks', label: 'Negative Remarks', type: 'text', section: 'Internal Conditions of Vehicle'),
    FormFieldSchema(key: 'original_reg_book', label: 'Original Reg Book', type: 'text', section: 'Document Review'),
    FormFieldSchema(key: 'original_cnic', label: 'Original Cnic', type: 'text', section: 'Document Review'),
    FormFieldSchema(key: 'original_eto', label: 'Original Eto', type: 'text', section: 'Document Review'),
    FormFieldSchema(key: 'hypothecated', label: 'Hypothecated', type: 'text', section: 'Document Review'),
    FormFieldSchema(key: 'duplicated_reg_book', label: 'Duplicated Reg Book', type: 'text', section: 'Document Review'),
    FormFieldSchema(key: 'vehicle_transfered', label: 'Vehicle Transfered', type: 'text', section: 'Document Review'),
    FormFieldSchema(key: 'vehicle_stolen', label: 'Vehicle Stolen', type: 'text', section: 'Document Review'),
    FormFieldSchema(key: 'total_assessed_value', label: 'Total Assessed Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate', label: 'Fsv Rate', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage', label: 'Is Percentage', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'calculated_fsv', label: 'Calculated Fsv', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value_second', label: 'Fsv Value Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate_second', label: 'Fsv Rate Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_type_second', label: 'Fsv Type Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated_second', label: 'Fsv Calculated Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'illustration_dealer', label: 'Illustration Dealer', type: 'text', section: 'Illustration (1)'),
    FormFieldSchema(key: 'illustration_dealer2', label: 'Illustration Dealer2', type: 'text', section: 'Illustration (2)'),
    FormFieldSchema(key: 'illustration_market_value', label: 'Illustration Market Value', type: 'number', section: 'Illustration (1)'),
    FormFieldSchema(key: 'illustration_market_value2', label: 'Illustration Market Value2', type: 'number', section: 'Illustration (2)'),
    FormFieldSchema(key: 'illustration_contact_no', label: 'Illustration Contact No', type: 'text', section: 'Illustration (1)'),
    FormFieldSchema(key: 'illustration_contact_no2', label: 'Illustration Contact No2', type: 'text', section: 'Illustration (2)'),
    FormFieldSchema(key: 'illustration_remarks2', label: 'Illustration Remarks2', type: 'text', section: 'Illustration (2)'),
    FormFieldSchema(key: 'maker', label: 'Maker', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'illustration_remarks', label: 'Illustration Remarks', type: 'text', section: 'Illustration (1)'),
  ];

  static final List<FormFieldSchema> mcbSchema = [
    FormFieldSchema(key: 'modal_status', label: 'Modal Status', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_date', label: 'Inspected Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'print_date', label: 'Print Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'representative_cnic', label: 'Representative Cnic', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_at', label: 'Inspected At', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'title_of_ownership', label: 'Title Of Ownership', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_make', label: 'Car Make', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_maker', label: 'Car Maker', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'car_model', label: 'Car Model', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_color', label: 'Car Color', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'bank_name', label: 'Bank Name', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'car_class', label: 'Car Class', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'air_conditionar_available', label: 'Air Conditionar Available', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'air_conditionar_working', label: 'Air Conditionar Working', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'car_registration', label: 'Car Registration', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration_date', label: 'Car Registration Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_cng_kit', label: 'Car Cng Kit', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'genre', label: 'Genre', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'car_engine_no', label: 'Car Engine No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'body_type', label: 'Body Type', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'car_engine_capacity', label: 'Car Engine Capacity', type: 'number', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_chassis_no', label: 'Car Chassis No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'odometer_reading', label: 'Odometer Reading', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'rim_type', label: 'Rim Type', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'manufactured', label: 'Manufactured', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'transmission', label: 'Transmission', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'feul_type', label: 'Feul Type', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'accessories', label: 'Accessories', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'car_drive', label: 'Car Drive', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'interior_condition', label: 'Interior Condition', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'is_hybrid', label: 'Is Hybrid', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'body_condition', label: 'Body Condition', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'engine_condition', label: 'Engine Condition', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'steering_control', label: 'Steering Control', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'axle', label: 'Axle', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'owner_address', label: 'Owner Address', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_maker', label: 'Car Maker', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'suspension', label: 'Suspension', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'seating_capacity', label: 'Seating Capacity', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'transmission_system', label: 'Transmission System', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'electric_system', label: 'Electric System', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'tyres', label: 'Tyres', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'ownership_per', label: 'Ownership Per', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'color_condition', label: 'Color Condition', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'any_leaks', label: 'Any Leaks', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'major_defects', label: 'Major Defects', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'chassis_repaired', label: 'Chassis Repaired', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'external_body', label: 'External Body', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'external_bonnet', label: 'External Bonnet', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'external_doors', label: 'External Doors', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'internal_dashboard', label: 'Internal Dashboard', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'internal_roof', label: 'Internal Roof', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'internal_seats', label: 'Internal Seats', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'overall_condition', label: 'Overall Condition', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'negative_remarks', label: 'Negative Remarks', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'original_reg_book', label: 'Original Reg Book', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'original_cnic', label: 'Original Cnic', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'original_eto', label: 'Original Eto', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'hypothecated', label: 'Hypothecated', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'duplicated_reg_book', label: 'Duplicated Reg Book', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'vehicle_transfered', label: 'Vehicle Transfered', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'vehicle_stolen', label: 'Vehicle Stolen', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'total_assessed_value', label: 'Total Assessed Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate', label: 'Fsv Rate', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value', label: 'Fsv Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage', label: 'Is Percentage', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'other1', label: 'Other1', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'other2', label: 'Other2', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'other3', label: 'Other3', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'other4', label: 'Other4', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'other5', label: 'Other5', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'other6', label: 'Other6', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'other7', label: 'Other7', type: 'text', section: 'Vehicle Condition'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value_second', label: 'Fsv Value Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate_second', label: 'Fsv Rate Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_type_second', label: 'Fsv Type Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated_second', label: 'Fsv Calculated Second', type: 'number', section: 'Valuation Details'),
  ];

  static final List<FormFieldSchema> bafSchema = [
    FormFieldSchema(key: 'inspected_date', label: 'Inspected Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'print_date', label: 'Print Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_time', label: 'Inspected Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_surveyor', label: 'Is Print Surveyor', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_time', label: 'Is Print Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_at', label: 'Inspected At', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'bank_name', label: 'Bank Name', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'title_of_ownership', label: 'Title Of Ownership', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_make', label: 'Car Make', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_model', label: 'Car Model', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_color', label: 'Car Color', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufacturing_year', label: 'Manufacturing Year', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'car_registration', label: 'Car Registration', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration_date', label: 'Car Registration Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_no', label: 'First Reg No', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'first_reg_date', label: 'First Reg Date', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'car_engine_no', label: 'Car Engine No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_capacity', label: 'Car Engine Capacity', type: 'number', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_chassis_no', label: 'Car Chassis No', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'odometer_reading', label: 'Odometer Reading', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'duplicate_book', label: 'Duplicate Book', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'original_book', label: 'Original Book', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'transmission_system', label: 'Transmission System', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'grade', label: 'Grade', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'acquired', label: 'Acquired', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'reconditioned', label: 'Reconditioned', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'repossesed', label: 'Repossesed', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'document_seen', label: 'Document Seen', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'is_push_start', label: 'Is Push Start', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'is_key_start', label: 'Is Key Start', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'manufactured', label: 'Manufactured', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'transmission', label: 'Transmission', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'feul_type', label: 'Feul Type', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'is_hybrid', label: 'Is Hybrid', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'car_cng_kit', label: 'Car Cng Kit', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'car_drive', label: 'Car Drive', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'right_side', label: 'Right Side', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'left_side', label: 'Left Side', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'front_side', label: 'Front Side', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'rear_side', label: 'Rear Side', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'show_grill', label: 'Show Grill', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'front_lower_shield', label: 'Front Lower Shield', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'front_back_bumper', label: 'Front Back Bumper', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'stolen_clearance_verbal', label: 'Stolen Clearance Verbal', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'stolen_clearance_physical', label: 'Stolen Clearance Physical', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'wheel_caps', label: 'Wheel Caps', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'monograms', label: 'Monograms', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'original_number_plates', label: 'Original Number Plates', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'shock_absorbers', label: 'Shock Absorbers', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'assemblies', label: 'Assemblies', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'tires', label: 'Tires', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'spare_tire', label: 'Spare Tire', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'tool_kit', label: 'Tool Kit', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'tickli', label: 'Tickli', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'seating_capacity', label: 'Seating Capacity', type: 'dropdown', section: 'General Info'),
    FormFieldSchema(key: 'ignition_takes', label: 'Ignition Takes', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'battery_starts', label: 'Battery Starts', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'engine', label: 'Engine', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'chassis', label: 'Chassis', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'radiator', label: 'Radiator', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'red_head_light', label: 'Red Head Light', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'left_head_light', label: 'Left Head Light', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'right_tail_light', label: 'Right Tail Light', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'left_tail_light', label: 'Left Tail Light', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'right_indicator_light', label: 'Right Indicator Light', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'left_indicator_light', label: 'Left Indicator Light', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'inner_lights', label: 'Inner Lights', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'steering_control', label: 'Steering Control', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'axle', label: 'Axle', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'clutch', label: 'Clutch', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'hypothecated_with', label: 'Hypothecated With', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'brakes', label: 'Brakes', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'hypothecated', label: 'Hypothecated', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'suspension', label: 'Suspension', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'air_conditionar_available', label: 'Air Conditionar Available', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'air_conditionar_working', label: 'Air Conditionar Working', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'heater_available', label: 'Heater Available', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'heater_working', label: 'Heater Working', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'cd_player_available', label: 'Cd Player Available', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'cd_player_working', label: 'Cd Player Working', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'cameras_available', label: 'Cameras Available', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'cameras_working', label: 'Cameras Working', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'other1', label: 'Other1', type: 'text', section: 'Comments'),
    FormFieldSchema(key: 'other2', label: 'Other2', type: 'text', section: 'Comments'),
    FormFieldSchema(key: 'other3', label: 'Other3', type: 'text', section: 'Comments'),
    FormFieldSchema(key: 'other4', label: 'Other4', type: 'text', section: 'Comments'),
    FormFieldSchema(key: 'other5', label: 'Other5', type: 'text', section: 'Comments'),
    FormFieldSchema(key: 'total_assessed_value', label: 'Total Assessed Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate', label: 'Fsv Rate', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage', label: 'Is Percentage', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'total_assessed_value2', label: 'Total Assessed Value2', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate2', label: 'Fsv Rate2', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage2', label: 'Is Percentage2', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'calculated_fsv', label: 'Calculated Fsv', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'electric_system', label: 'Electric System', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'body_condition', label: 'Body Condition', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'engine_condition', label: 'Engine Condition', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value_second', label: 'Fsv Value Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate_second', label: 'Fsv Rate Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_type_second', label: 'Fsv Type Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated_second', label: 'Fsv Calculated Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'verbal_time', label: 'Verbal Time', type: 'text', section: 'Section B - Conditions of Vehicle'),
    FormFieldSchema(key: 'is_print_verbal', label: 'Is Print Verbal', type: 'text', section: 'Section B - Conditions of Vehicle'),
  ];

  static final List<FormFieldSchema> fsblSchema = [
    FormFieldSchema(key: 'inspected_date', label: 'Inspected Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'print_date', label: 'Print Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_time', label: 'Inspected Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_surveyor', label: 'Is Print Surveyor', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_time', label: 'Is Print Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_at', label: 'Inspected At', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'bank_name', label: 'Bank Name', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'title_of_ownership', label: 'Title Of Ownership', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_make', label: 'Car Make', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_model', label: 'Car Model', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_color', label: 'Car Color', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufacturing_year', label: 'Manufacturing Year', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration', label: 'Car Registration', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration_date', label: 'Car Registration Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_no', label: 'First Reg No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_date', label: 'First Reg Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_no', label: 'Car Engine No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_capacity', label: 'Car Engine Capacity', type: 'number', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_chassis_no', label: 'Car Chassis No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'odometer_reading', label: 'Odometer Reading', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'grade', label: 'Grade', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'acquired', label: 'Acquired', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'reconditioned', label: 'Reconditioned', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'repossesed', label: 'Repossesed', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'document_seen', label: 'Document Seen', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_push_start', label: 'Is Push Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_key_start', label: 'Is Key Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufactured', label: 'Manufactured', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'transmission', label: 'Transmission', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'feul_type', label: 'Feul Type', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_hybrid', label: 'Is Hybrid', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_cng_kit', label: 'Car Cng Kit', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_drive', label: 'Car Drive', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'right_side', label: 'Right Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'left_side', label: 'Left Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_side', label: 'Front Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'rear_side', label: 'Rear Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'show_grill', label: 'Show Grill', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_lower_shield', label: 'Front Lower Shield', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_back_bumper', label: 'Front Back Bumper', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'wheel_caps', label: 'Wheel Caps', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'monograms', label: 'Monograms', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'original_number_plates', label: 'Original Number Plates', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'shock_absorbers', label: 'Shock Absorbers', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'assemblies', label: 'Assemblies', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tires', label: 'Tires', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'spare_tire', label: 'Spare Tire', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tool_kit', label: 'Tool Kit', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tickli', label: 'Tickli', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'seating_capacity', label: 'Seating Capacity', type: 'dropdown', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'ignition_takes', label: 'Ignition Takes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'battery_starts', label: 'Battery Starts', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'engine', label: 'Engine', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'chassis', label: 'Chassis', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'radiator', label: 'Radiator', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'red_head_light', label: 'Red Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_head_light', label: 'Left Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_tail_light', label: 'Right Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_tail_light', label: 'Left Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_indicator_light', label: 'Right Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_indicator_light', label: 'Left Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'inner_lights', label: 'Inner Lights', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'steering_control', label: 'Steering Control', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'axle', label: 'Axle', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'clutch', label: 'Clutch', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'brakes', label: 'Brakes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'suspension', label: 'Suspension', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'air_conditionar_available', label: 'Air Conditionar Available', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'air_conditionar_working', label: 'Air Conditionar Working', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'heater_available', label: 'Heater Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'heater_working', label: 'Heater Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_available', label: 'Cd Player Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_working', label: 'Cd Player Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_available', label: 'Cameras Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_working', label: 'Cameras Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'other1', label: 'Other1', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other2', label: 'Other2', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other3', label: 'Other3', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other4', label: 'Other4', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other5', label: 'Other5', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'total_assessed_value', label: 'Total Assessed Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate', label: 'Fsv Rate', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage', label: 'Is Percentage', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value_second', label: 'Fsv Value Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated', label: 'Fsv Calculated', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate_second', label: 'Fsv Rate Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_type_second', label: 'Fsv Type Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated_second', label: 'Fsv Calculated Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_hide', label: 'Is Hide', type: 'text', section: 'Valuation Details'),
  ];

  static final List<FormFieldSchema> mblSchema = [
    FormFieldSchema(key: 'inspected_date', label: 'Inspected Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'print_date', label: 'Print Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_time', label: 'Inspected Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_surveyor', label: 'Is Print Surveyor', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_time', label: 'Is Print Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_at', label: 'Inspected At', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'bank_name', label: 'Bank Name', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'title_of_ownership', label: 'Title Of Ownership', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_make', label: 'Car Make', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_model', label: 'Car Model', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_color', label: 'Car Color', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufacturing_year', label: 'Manufacturing Year', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration', label: 'Car Registration', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration_date', label: 'Car Registration Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_no', label: 'First Reg No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_date', label: 'First Reg Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_no', label: 'Car Engine No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_capacity', label: 'Car Engine Capacity', type: 'number', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_chassis_no', label: 'Car Chassis No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'odometer_reading', label: 'Odometer Reading', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'grade', label: 'Grade', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'acquired', label: 'Acquired', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'reconditioned', label: 'Reconditioned', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'repossesed', label: 'Repossesed', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'document_seen', label: 'Document Seen', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_push_start', label: 'Is Push Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_key_start', label: 'Is Key Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufactured', label: 'Manufactured', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'transmission', label: 'Transmission', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'feul_type', label: 'Feul Type', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_hybrid', label: 'Is Hybrid', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_cng_kit', label: 'Car Cng Kit', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_drive', label: 'Car Drive', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'right_side', label: 'Right Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'left_side', label: 'Left Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_side', label: 'Front Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'rear_side', label: 'Rear Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'show_grill', label: 'Show Grill', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_lower_shield', label: 'Front Lower Shield', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_back_bumper', label: 'Front Back Bumper', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'wheel_caps', label: 'Wheel Caps', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'monograms', label: 'Monograms', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'original_number_plates', label: 'Original Number Plates', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'shock_absorbers', label: 'Shock Absorbers', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'assemblies', label: 'Assemblies', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tires', label: 'Tires', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'spare_tire', label: 'Spare Tire', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tool_kit', label: 'Tool Kit', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tickli', label: 'Tickli', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'seating_capacity', label: 'Seating Capacity', type: 'dropdown', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'ignition_takes', label: 'Ignition Takes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'battery_starts', label: 'Battery Starts', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'engine', label: 'Engine', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'chassis', label: 'Chassis', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'radiator', label: 'Radiator', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'red_head_light', label: 'Red Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_head_light', label: 'Left Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_tail_light', label: 'Right Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_tail_light', label: 'Left Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_indicator_light', label: 'Right Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_indicator_light', label: 'Left Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'inner_lights', label: 'Inner Lights', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'steering_control', label: 'Steering Control', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'axle', label: 'Axle', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'clutch', label: 'Clutch', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'brakes', label: 'Brakes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'suspension', label: 'Suspension', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'air_conditionar_available', label: 'Air Conditionar Available', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'air_conditionar_working', label: 'Air Conditionar Working', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'heater_available', label: 'Heater Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'heater_working', label: 'Heater Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_available', label: 'Cd Player Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_working', label: 'Cd Player Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_available', label: 'Cameras Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_working', label: 'Cameras Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'other1', label: 'Other1', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other2', label: 'Other2', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other3', label: 'Other3', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other4', label: 'Other4', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other5', label: 'Other5', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'total_assessed_value', label: 'Total Assessed Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate', label: 'Fsv Rate', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage', label: 'Is Percentage', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'total_assessed_value2', label: 'Total Assessed Value2', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value_second', label: 'Fsv Value Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate_second', label: 'Fsv Rate Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_type_second', label: 'Fsv Type Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated_second', label: 'Fsv Calculated Second', type: 'number', section: 'Valuation Details'),
  ];

  static final List<FormFieldSchema> mmbSchema = [
    FormFieldSchema(key: 'inspected_date', label: 'Inspected Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'print_date', label: 'Print Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_time', label: 'Inspected Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_surveyor', label: 'Is Print Surveyor', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_time', label: 'Is Print Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_at', label: 'Inspected At', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'bank_name', label: 'Bank Name', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'title_of_ownership', label: 'Title Of Ownership', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_make', label: 'Car Make', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_model', label: 'Car Model', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_color', label: 'Car Color', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufacturing_year', label: 'Manufacturing Year', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration', label: 'Car Registration', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration_date', label: 'Car Registration Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_no', label: 'First Reg No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_date', label: 'First Reg Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_no', label: 'Car Engine No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_capacity', label: 'Car Engine Capacity', type: 'number', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_chassis_no', label: 'Car Chassis No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'odometer_reading', label: 'Odometer Reading', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'grade', label: 'Grade', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'acquired', label: 'Acquired', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'reconditioned', label: 'Reconditioned', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'repossesed', label: 'Repossesed', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'document_seen', label: 'Document Seen', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_push_start', label: 'Is Push Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_key_start', label: 'Is Key Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufactured', label: 'Manufactured', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'transmission', label: 'Transmission', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'feul_type', label: 'Feul Type', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_hybrid', label: 'Is Hybrid', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_cng_kit', label: 'Car Cng Kit', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_drive', label: 'Car Drive', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'right_side', label: 'Right Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'left_side', label: 'Left Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_side', label: 'Front Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'rear_side', label: 'Rear Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'show_grill', label: 'Show Grill', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_lower_shield', label: 'Front Lower Shield', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_back_bumper', label: 'Front Back Bumper', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'wheel_caps', label: 'Wheel Caps', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'monograms', label: 'Monograms', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'original_number_plates', label: 'Original Number Plates', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'shock_absorbers', label: 'Shock Absorbers', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'assemblies', label: 'Assemblies', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tires', label: 'Tires', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'spare_tire', label: 'Spare Tire', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tool_kit', label: 'Tool Kit', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tickli', label: 'Tickli', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'seating_capacity', label: 'Seating Capacity', type: 'dropdown', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'ignition_takes', label: 'Ignition Takes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'battery_starts', label: 'Battery Starts', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'engine', label: 'Engine', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'chassis', label: 'Chassis', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'radiator', label: 'Radiator', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'red_head_light', label: 'Red Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_head_light', label: 'Left Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_tail_light', label: 'Right Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_tail_light', label: 'Left Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_indicator_light', label: 'Right Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_indicator_light', label: 'Left Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'inner_lights', label: 'Inner Lights', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'steering_control', label: 'Steering Control', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'axle', label: 'Axle', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'clutch', label: 'Clutch', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'brakes', label: 'Brakes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'suspension', label: 'Suspension', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'air_conditionar_available', label: 'Air Conditionar Available', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'air_conditionar_working', label: 'Air Conditionar Working', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'heater_available', label: 'Heater Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'heater_working', label: 'Heater Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_available', label: 'Cd Player Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_working', label: 'Cd Player Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_available', label: 'Cameras Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_working', label: 'Cameras Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'other1', label: 'Other1', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other2', label: 'Other2', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other3', label: 'Other3', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other4', label: 'Other4', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other5', label: 'Other5', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'total_assessed_value', label: 'Total Assessed Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate', label: 'Fsv Rate', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage', label: 'Is Percentage', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'total_assessed_value2', label: 'Total Assessed Value2', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value_second', label: 'Fsv Value Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate_second', label: 'Fsv Rate Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_type_second', label: 'Fsv Type Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated_second', label: 'Fsv Calculated Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_hide', label: 'Is Hide', type: 'text', section: 'Valuation Details'),
  ];

  static final List<FormFieldSchema> smblSchema = [
    FormFieldSchema(key: 'inspected_date', label: 'Inspected Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'print_date', label: 'Print Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_time', label: 'Inspected Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_surveyor', label: 'Is Print Surveyor', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_time', label: 'Is Print Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_at', label: 'Inspected At', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'bank_name', label: 'Bank Name', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'title_of_ownership', label: 'Title Of Ownership', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_make', label: 'Car Make', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_model', label: 'Car Model', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_color', label: 'Car Color', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufacturing_year', label: 'Manufacturing Year', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration', label: 'Car Registration', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration_date', label: 'Car Registration Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_no', label: 'First Reg No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_date', label: 'First Reg Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_no', label: 'Car Engine No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_capacity', label: 'Car Engine Capacity', type: 'number', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_chassis_no', label: 'Car Chassis No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'odometer_reading', label: 'Odometer Reading', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'grade', label: 'Grade', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'acquired', label: 'Acquired', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'reconditioned', label: 'Reconditioned', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'repossesed', label: 'Repossesed', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'document_seen', label: 'Document Seen', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_push_start', label: 'Is Push Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_key_start', label: 'Is Key Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufactured', label: 'Manufactured', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'transmission', label: 'Transmission', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'feul_type', label: 'Feul Type', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_hybrid', label: 'Is Hybrid', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_cng_kit', label: 'Car Cng Kit', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_drive', label: 'Car Drive', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'right_side', label: 'Right Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'left_side', label: 'Left Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_side', label: 'Front Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'rear_side', label: 'Rear Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'show_grill', label: 'Show Grill', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_lower_shield', label: 'Front Lower Shield', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_back_bumper', label: 'Front Back Bumper', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'wheel_caps', label: 'Wheel Caps', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'monograms', label: 'Monograms', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'original_number_plates', label: 'Original Number Plates', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'shock_absorbers', label: 'Shock Absorbers', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'assemblies', label: 'Assemblies', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tires', label: 'Tires', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'spare_tire', label: 'Spare Tire', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tool_kit', label: 'Tool Kit', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tickli', label: 'Tickli', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'seating_capacity', label: 'Seating Capacity', type: 'dropdown', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'ignition_takes', label: 'Ignition Takes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'battery_starts', label: 'Battery Starts', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'engine', label: 'Engine', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'chassis', label: 'Chassis', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'radiator', label: 'Radiator', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'red_head_light', label: 'Red Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_head_light', label: 'Left Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_tail_light', label: 'Right Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_tail_light', label: 'Left Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_indicator_light', label: 'Right Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_indicator_light', label: 'Left Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'inner_lights', label: 'Inner Lights', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'steering_control', label: 'Steering Control', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'axle', label: 'Axle', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'clutch', label: 'Clutch', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'brakes', label: 'Brakes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'suspension', label: 'Suspension', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'air_conditionar_available', label: 'Air Conditionar Available', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'air_conditionar_working', label: 'Air Conditionar Working', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'heater_available', label: 'Heater Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'heater_working', label: 'Heater Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_available', label: 'Cd Player Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_working', label: 'Cd Player Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_available', label: 'Cameras Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_working', label: 'Cameras Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'other1', label: 'Other1', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other2', label: 'Other2', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other3', label: 'Other3', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other4', label: 'Other4', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other5', label: 'Other5', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'total_assessed_value', label: 'Total Assessed Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate', label: 'Fsv Rate', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage', label: 'Is Percentage', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated', label: 'Fsv Calculated', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value_second', label: 'Fsv Value Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate_second', label: 'Fsv Rate Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_type_second', label: 'Fsv Type Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated_second', label: 'Fsv Calculated Second', type: 'number', section: 'Valuation Details'),
  ];

  static final List<FormFieldSchema> othersSchema = [
    FormFieldSchema(key: 'inspected_date', label: 'Inspected Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'print_date', label: 'Print Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_time', label: 'Inspected Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_surveyor', label: 'Is Print Surveyor', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_print_time', label: 'Is Print Time', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'inspected_at', label: 'Inspected At', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'bank_name', label: 'Bank Name', type: 'text', section: 'General Info'),
    FormFieldSchema(key: 'title_of_ownership', label: 'Title Of Ownership', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_make', label: 'Car Make', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_model', label: 'Car Model', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_color', label: 'Car Color', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufacturing_year', label: 'Manufacturing Year', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration', label: 'Car Registration', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_registration_date', label: 'Car Registration Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_no', label: 'First Reg No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'first_reg_date', label: 'First Reg Date', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_no', label: 'Car Engine No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_engine_capacity', label: 'Car Engine Capacity', type: 'number', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_chassis_no', label: 'Car Chassis No', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'odometer_reading', label: 'Odometer Reading', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'grade', label: 'Grade', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'acquired', label: 'Acquired', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'reconditioned', label: 'Reconditioned', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'repossesed', label: 'Repossesed', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'document_seen', label: 'Document Seen', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_push_start', label: 'Is Push Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_key_start', label: 'Is Key Start', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'manufactured', label: 'Manufactured', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'transmission', label: 'Transmission', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'feul_type', label: 'Feul Type', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'is_hybrid', label: 'Is Hybrid', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_cng_kit', label: 'Car Cng Kit', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'car_drive', label: 'Car Drive', type: 'dropdown', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'right_side', label: 'Right Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'left_side', label: 'Left Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_side', label: 'Front Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'rear_side', label: 'Rear Side', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'show_grill', label: 'Show Grill', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_lower_shield', label: 'Front Lower Shield', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'front_back_bumper', label: 'Front Back Bumper', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'wheel_caps', label: 'Wheel Caps', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'monograms', label: 'Monograms', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'original_number_plates', label: 'Original Number Plates', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'shock_absorbers', label: 'Shock Absorbers', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'assemblies', label: 'Assemblies', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tires', label: 'Tires', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'spare_tire', label: 'Spare Tire', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tool_kit', label: 'Tool Kit', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'tickli', label: 'Tickli', type: 'text', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'seating_capacity', label: 'Seating Capacity', type: 'dropdown', section: 'Physical (Body) Conditions of Vehicle'),
    FormFieldSchema(key: 'ignition_takes', label: 'Ignition Takes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'battery_starts', label: 'Battery Starts', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'engine', label: 'Engine', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'chassis', label: 'Chassis', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'radiator', label: 'Radiator', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'red_head_light', label: 'Red Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_head_light', label: 'Left Head Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_tail_light', label: 'Right Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_tail_light', label: 'Left Tail Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'right_indicator_light', label: 'Right Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'left_indicator_light', label: 'Left Indicator Light', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'inner_lights', label: 'Inner Lights', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'steering_control', label: 'Steering Control', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'axle', label: 'Axle', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'clutch', label: 'Clutch', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'brakes', label: 'Brakes', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'suspension', label: 'Suspension', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'air_conditionar_available', label: 'Air Conditionar Available', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'air_conditionar_working', label: 'Air Conditionar Working', type: 'text', section: 'Vehicle\'s Details'),
    FormFieldSchema(key: 'heater_available', label: 'Heater Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'heater_working', label: 'Heater Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_available', label: 'Cd Player Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cd_player_working', label: 'Cd Player Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_available', label: 'Cameras Available', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'cameras_working', label: 'Cameras Working', type: 'text', section: 'Electro-Mechanical Conditions of Vehicle'),
    FormFieldSchema(key: 'other1', label: 'Other1', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other2', label: 'Other2', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other3', label: 'Other3', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other4', label: 'Other4', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'other5', label: 'Other5', type: 'text', section: 'Others'),
    FormFieldSchema(key: 'total_assessed_value', label: 'Total Assessed Value', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate', label: 'Fsv Rate', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage', label: 'Is Percentage', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'total_assessed_value2', label: 'Total Assessed Value2', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate2', label: 'Fsv Rate2', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_percentage2', label: 'Is Percentage2', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'calculated_fsv', label: 'Calculated Fsv', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'is_reg_book', label: 'Is Reg Book', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'second_val', label: 'Second Val', type: 'text', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_value_second', label: 'Fsv Value Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_rate_second', label: 'Fsv Rate Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_type_second', label: 'Fsv Type Second', type: 'number', section: 'Valuation Details'),
    FormFieldSchema(key: 'fsv_calculated_second', label: 'Fsv Calculated Second', type: 'number', section: 'Valuation Details'),
  ];

  static final Map<String, List<FormFieldSchema>> schemas = {
    'ASKBL': askblSchema,
    'MCB': mcbSchema,
    'BAF': bafSchema,
    'FSBL': fsblSchema,
    'MBL': mblSchema,
    'MMB': mmbSchema,
    'SMBL': smblSchema,
    'OTHERS': othersSchema,
  };
}